### ISSUE TITLE
Copying the content of a post and clicking on "Save and reload this page" doesn't work

### ISSUE THREAD

**Issue by davilera** [inpsyde/MultilingualPress#295] opened 2017-11-02 10:19 UTC
#### Version Information

* PHP: 7
* WordPress: 4.8.3

#### Steps to Reproduce

1. Create a new post in one language
2. Save the draft
3. Look for the Translation meta box
4. Click on _Copy source post_ (and maybe enable the checkbox for copying the feat. image)
5. Click on _Change relationship_
6. Select _Create new post_
7. Click on _Save and reload this page_

#### What I Expected

The translated post should have the same title, slug, post content, excerpt (and possibly featured image) as the original post.

#### What Happened Instead

Only the title and slug were copied. Post content, excerpt, and featured images remain empty.

If I want those fields to be copied, I have to reclick on _Copy source post_ and then _Save_ the original post using the _Save_ button in the _Publish_ meta box.

**Comment by tfrommen** [comment] 2017-11-03 07:48
duplicate #264

----

Hi there,

this is by design.

The option _Create new post_ does **not** take the data you might have input and creates a new post with that. Instead, an empty post with only the title of the original one is being created.

We already have #264, so I will close this one as duplicate. Due to the reference, your issue will show up on the other one, so what you wrote is not lost.

Thanks,
Thorsten

**Closed by tfrommen** 2017-11-03 07:48 UTC
